package cozy.archive

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path}
import java.security.MessageDigest

import org.scalatest.GivenWhenThen
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec
import play.api.libs.json.{JsArray, JsObject, JsString, Json}

/*
 * @since   Aug. 24, 2026
 * @version Aug. 24, 2026
 * @author  ASAMI, Tomoharu
 */
final class ComponentSourceArchiveProjectionSpec
    extends AnyWordSpec
    with Matchers
    with GivenWhenThen {
  "ComponentSourceArchiveProjection" should {
    "DOC03-SRC-AC-01 emit canonical entries and JSON" which {
      "write sorted relative entries in the fixed v1 JSON field order" in {
        _with_temp_dir("cozy-doc03-source-archive-canonical") { projectroot =>
          Given("a project containing admitted source files and root documents")
          val contents = Vector(
            "src/main/cozy/model.cml" -> "component Model\n",
            "src/test/cozy/model-test.cml" -> "specification Model\n",
            "project.yaml" -> "project:\n  kind: component\n",
            "build.sbt" -> "name := \"model\"\n",
            "README.md" -> "# Model\n"
          )
          contents.foreach { case (relativepath, content) =>
            _write(projectroot.resolve(relativepath), content)
          }

          When("the source inventory is projected and rendered as JSON")
          val archive = ComponentSourceArchiveProjection.project(projectroot)
          val rendered = ComponentSourceArchiveProjection.render(archive)
          val json = Json.parse(rendered).as[JsObject]
          val expectedentries = contents.map { case (path, content) =>
            path -> _sha256(content)
          }.sortBy(_._1)
          val expecteddigest = _sha256(expectedentries.map {
            case (path, digest) => s"$path\t$digest\n"
          }.mkString)

          Then("the canonical JSON is structurally valid and has only fixed-order inventory evidence")
          archive.entries.map(entry => entry.path -> entry.sha256) shouldBe expectedentries
          archive.archiveDigest shouldBe expecteddigest
          rendered shouldBe _canonical_json(expecteddigest, expectedentries)
          json.value("schema") shouldBe JsString("cozy.component-source-archive.v1")
          json.value("archiveDigest") shouldBe JsString(expecteddigest)
          _entries(json) shouldBe expectedentries
          rendered should not include projectroot.toAbsolutePath.normalize().toString
          rendered should not include "provenance"
        }
      }
    }

    "DOC03-SRC-AC-02 exclude hostile and host state" which {
      "omit generated, transient, secret, and symbolic-link material from paths and digest provenance" in {
        _with_temp_dir("cozy-doc03-source-archive-hostile") { projectroot =>
          Given("an admitted source alongside generated, host-local, and symbolic-link material")
          val admitted = "src/main/cozy/model.cml" -> "component Model\n"
          _write(projectroot.resolve(admitted._1), admitted._2)
          val hostile = Vector(
            "src/main/cozy/generated.class" -> "class bytes\n",
            "src/main/cozy/generated.jar" -> "jar bytes\n",
            "src/main/cozy/build.log" -> "log bytes\n",
            "src/main/cozy/build.temp" -> "temp bytes\n",
            "src/main/cozy/build.tmp" -> "tmp bytes\n",
            "src/main/.env.local" -> "secret bytes\n",
            "src/main/cozy/cache/value.bin" -> "cache bytes\n",
            "src/main/cozy/host-local/value.bin" -> "host bytes\n",
            "target/generated.txt" -> "generated bytes\n",
            ".git/config" -> "git bytes\n",
            ".env" -> "environment bytes\n",
            "local.conf" -> "local configuration bytes\n",
            "log/output.txt" -> "root log bytes\n"
          )
          hostile.foreach { case (relativepath, content) =>
            _write(projectroot.resolve(relativepath), content)
          }
          val linkpath = projectroot.resolve("src/main/cozy/generated-alias.cml")
          Files.createSymbolicLink(linkpath, linkpath.getParent.relativize(projectroot.resolve("target/generated.txt")))

          When("the source inventory is projected and an outside-target writer path is requested")
          val archive = ComponentSourceArchiveProjection.project(projectroot)
          val rendered = ComponentSourceArchiveProjection.render(archive)
          val outsidewrite = the[IllegalArgumentException] thrownBy {
            ComponentSourceArchiveProjection.write(projectroot, projectroot.resolve("source-archive.json"))
          }

          Then("only admitted paths remain and hostile names, bytes, host paths, and unsafe outputs are absent")
          archive.entries.map(_.path) shouldBe Vector(admitted._1)
          hostile.foreach { case (relativepath, content) =>
            rendered should not include relativepath
            rendered should not include content.trim
          }
          rendered should not include "src/main/cozy/generated-alias.cml"
          rendered should not include projectroot.toAbsolutePath.normalize().toString
          outsidewrite.getMessage should include("target directory")
        }
      }
    }

    "DOC03-SRC-AC-03 preserve writer bytes and digests across repeats" which {
      "write byte-identical canonical output under target without including its own output" in {
        _with_temp_dir("cozy-doc03-source-archive-repeat") { projectroot =>
          Given("an unchanged ordinary project and a target path that does not yet exist")
          val contents = Vector(
            "src/main/cozy/model.cml" -> "component Model\n",
            "README.md" -> "# Model\n"
          )
          contents.foreach { case (relativepath, content) =>
            _write(projectroot.resolve(relativepath), content)
          }
          val output = projectroot.resolve("target/cozy/component-source-archive.json")

          When("the canonical writer runs twice against the same project")
          val firstpath = ComponentSourceArchiveProjection.write(projectroot, output)
          val firstbytes = Files.readAllBytes(firstpath)
          val firstjson = Json.parse(new String(firstbytes, StandardCharsets.UTF_8)).as[JsObject]
          val secondpath = ComponentSourceArchiveProjection.write(projectroot, output)
          val secondbytes = Files.readAllBytes(secondpath)
          val secondjson = Json.parse(new String(secondbytes, StandardCharsets.UTF_8)).as[JsObject]

          Then("the target-only writer creates deterministic bytes, entries, and archive digest")
          firstpath shouldBe output
          secondpath shouldBe output
          java.util.Arrays.equals(firstbytes, secondbytes) shouldBe true
          _entries(firstjson) shouldBe _entries(secondjson)
          (firstjson \ "archiveDigest").as[String] shouldBe (secondjson \ "archiveDigest").as[String]
          _entries(secondjson).map(_._1) shouldBe contents.map(_._1).sorted
          _entries(secondjson).map(_._1) should not contain "target/cozy/component-source-archive.json"
          firstbytes.last should not be '\n'.toByte
        }
      }
    }
  }

  private def _entries(json: JsObject): Vector[(String, String)] =
    (json \ "entries").as[JsArray].value.toVector.map { value =>
      val entry = value.as[JsObject]
      (entry \ "path").as[String] -> (entry \ "sha256").as[String]
    }

  private def _canonical_json(archiveDigest: String, entries: Vector[(String, String)]): String =
    s"""{"schema":"cozy.component-source-archive.v1","archiveDigest":"$archiveDigest","entries":""" +
      entries.map { case (path, digest) =>
        s"""{"path":"$path","sha256":"$digest"}"""
      }.mkString("[", ",", "]") + "}"

  private def _with_temp_dir[A](prefix: String)(f: Path => A): A = {
    val directory = Files.createTempDirectory(prefix)
    try f(directory)
    finally _delete_tree(directory)
  }

  private def _write(path: Path, content: String): Path = {
    val parent = path.getParent
    if (parent != null) Files.createDirectories(parent)
    Files.write(path, content.getBytes(StandardCharsets.UTF_8))
  }

  private def _delete_tree(path: Path): Unit = {
    if (Files.exists(path)) {
      val stream = Files.walk(path)
      try stream.sorted(java.util.Comparator.reverseOrder()).forEach(path => Files.deleteIfExists(path))
      finally stream.close()
    }
  }

  private def _sha256(content: String): String =
    MessageDigest
      .getInstance("SHA-256")
      .digest(content.getBytes(StandardCharsets.UTF_8))
      .map(byte => f"${byte & 0xff}%02x")
      .mkString
}
