package cozy.modeler

import java.io.ByteArrayOutputStream
import java.io.PrintStream
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Paths
import scala.collection.JavaConverters._
import org.scalatest.GivenWhenThen
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec
import org.goldenport.kaleidox.{Config => KaleidoxConfig, Model => KaleidoxModel}
import org.goldenport.record.v2.{CFormat, CMaxLength, CMinLength, CRegex}
import org.goldenport.collection.VectorMap
import org.simplemodeling.model._
import org.simplemodeling.model.domain.MDomainStateMachine
import org.simplemodeling.SimpleModeler.generators.scala.Scala3StateMachineGenerator
import org.simplemodeling.SimpleModeler.transformer.scala.ScalaModelTransformer
import org.simplemodeling.SimpleModeler.transformers.scala.StateMachineScalaModelTransformer
import org.smartdox.Description

/*
 * @since   Jun. 23, 2026
 * @version Aug. 30, 2026
 * @author  ASAMI, Tomoharu
 */
class ModelerValueGenerationSpec extends AnyWordSpec with Matchers with GivenWhenThen with ModelerSpecSupport {
  "CML value model generation" should {
    "generate value-side models" which {
      "modeler-scala-value generates value model without component" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/test.dox")
        val out = base.resolve("target/test-generated/modeler-scala-value")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates the value-side model artifacts")
        cozy.Cozy.main(Array("modeler-scala-value", input.toString, "--save", out.toString.toString))

        val entity = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/Person.scala"
        )
        val query = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/query/Person.scala"
        )
        val domaincomponent = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        Then("the generated values preserve the source model semantics")
        withClue(s"generated entity file not found: $entity") {
        Files.exists(entity) shouldBe true
      }
        withClue(s"generated query value file not found: $query") {
        Files.exists(query) shouldBe true
      }
        withClue(s"DomainComponent must not be generated in value mode: $domaincomponent") {
        Files.exists(domaincomponent) shouldBe false
      }
      }

      "modeler-scala-value accepts VALUE-only cml without component generation" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/value-only-literate.dox")
        val out = base.resolve("target/test-generated/modeler-scala-value-value-only")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates the value-side model artifacts")
        cozy.Cozy.main(Array("modeler-scala-value", input.toString, "--save", out.toString.toString))

        val buildsbt = out.resolve("build.sbt")
        val value = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/value/CountryCode.scala"
        )
        val entity = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/CountryCode.scala"
        )
        val domaincomponent = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        Then("the generated values preserve the source model semantics")
        withClue(s"build.sbt must not be generated by default: $buildsbt") {
        Files.exists(buildsbt) shouldBe false
      }
        withClue(s"value file not found: $value") {
        Files.exists(value) shouldBe true
      }
        withClue(s"entity file must not be generated from VALUE section: $entity") {
        Files.exists(entity) shouldBe false
      }
        withClue(s"DomainComponent must not be generated in value mode: $domaincomponent") {
        Files.exists(domaincomponent) shouldBe false
      }
      }

      "modeler-scala-value honors explicit VALUE package and local value references" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-input/modeler-scala-value-explicit-package.cml")
        val out = base.resolve("target/test-generated/modeler-scala-value-explicit-package")
        delete_recursively(out)
        write_file(input,
        """# VALUE
          |
          |## InformationId
          |
          |package = org.goldenport.cncf.information
          |
          |### ATTRIBUTE
          |
          || name  | type   | multiplicity |
          ||-------|--------|--------------|
          || value | string | 1            |
          |
          |## EditableInformation
          |
          |package = org.goldenport.cncf.information
          |
          |### ATTRIBUTE
          |
          || name          | type          | multiplicity |
          ||---------------|---------------|--------------|
          || informationId | InformationId | 1            |
          |""".stripMargin)

        When("Cozy generates the value-side model artifacts")
        val model = KaleidoxModel.load(KaleidoxConfig.default.withoutLocation, input.toFile)
        val simplemodel = new cozy.modeler.Modeler().buildValueModel(model)
        Then("the generated values preserve the source model semantics")
        val editablevalue = simplemodel.elements.collectFirst {
        case m: org.simplemodeling.model.domain.MDomainValue if m.name == "EditableInformation" => m
      }.getOrElse(fail("EditableInformation value is missing"))
        val idattribute = editablevalue.attributes.find(_.name == "informationId").getOrElse(fail("informationId attribute is missing"))
        withClue(s"informationId must be object typed: ${idattribute.attributeType}") {
        idattribute.attributeType.isInstanceOf[org.simplemodeling.model.MObjectAttributeType] shouldBe true
      }

        cozy.Cozy.main(Array("modeler-scala-value", input.toString, "--save", out.toString.toString))

        val informationid = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/org/goldenport/cncf/information/InformationId.scala"
        )
        val editable = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/org/goldenport/cncf/information/EditableInformation.scala"
        )
        withClue(s"value file not found: $informationid") {
        Files.exists(informationid) shouldBe true
      }
        withClue(s"value file not found: $editable") {
        Files.exists(editable) shouldBe true
      }
        val content = Files.readString(editable)
        withClue(s"local value reference must stay typed: $content") {
        content should include ("informationId: InformationId")
      }
      }

      "modeler-scala-value accepts powertype-only cml without component generation" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/powertype-literate.dox")
        val out = base.resolve("target/test-generated/modeler-scala-value-powertype-only")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates the value-side model artifacts")
        cozy.Cozy.main(Array("modeler-scala-value", input.toString, "--save", out.toString.toString))

        val buildsbt = out.resolve("build.sbt")
        val countrycode = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/value/CountryCode.scala"
        )
        val addresstype = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/value/AddressType.scala"
        )
        val domaincomponent = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        Then("the generated values preserve the source model semantics")
        withClue(s"build.sbt must not be generated by default: $buildsbt") {
        Files.exists(buildsbt) shouldBe false
      }
        withClue(s"powertype file not found: $countrycode") {
        Files.exists(countrycode) shouldBe true
      }
        withClue(s"powertype file not found: $addresstype") {
        Files.exists(addresstype) shouldBe true
      }
        withClue(s"DomainComponent must not be generated in value mode: $domaincomponent") {
        Files.exists(domaincomponent) shouldBe false
      }
      }

      "modeler-scala-value accepts statemachine-only cml without component generation" in {
        Given("a top-level CML StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/statemachine-division-alias.dox")
        val out = base.resolve("target/test-generated/modeler-scala-value-statemachine-only")
        val buildsbt = out.resolve("build.sbt")
        val lifecycle = out.resolve(
          "target/scala-3.3.8/src_managed/main/scala/domain/statemachine/lifecycle.scala"
        )
        val domaincomponent = out.resolve(
          "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates the value-side StateMachine descriptor")
        cozy.Cozy.main(Array("modeler-scala-value", input.toString, "--save", out.toString.toString))

        Then("the descriptor preserves ordered topology without a component")
        withClue(s"build.sbt must not be generated by default: $buildsbt") {
          Files.exists(buildsbt) shouldBe false
        }
        withClue(s"statemachine file not found: $lifecycle") {
          Files.exists(lifecycle) shouldBe true
        }
        withClue(s"DomainComponent must not be generated in value mode: $domaincomponent") {
          Files.exists(domaincomponent) shouldBe false
        }
        val content = Files.readString(lifecycle)
        withClue(s"state-machine descriptor source must preserve topology: $content") {
          content should include ("object lifecycle {")
          content should include ("value: Either[String, Int]")
          content should include ("State(\"Draft\", Right(10))")
          content should include ("Transition(\"Draft\", Some(\"publish\"), \"Published\")")
          content should include ("event: Option[String]")
          content should include ("def permits(from: String, event: String, to: String): Boolean =")
          content should include ("transition.event.contains(event)")
          content.indexOf("State(\"Draft\", Right(10))") should be < content.indexOf("State(\"Published\", Right(2))")
        }
      }

      "modeler-scala-value accepts powertype-only .cml with literate narrative" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/powertype-literate.cml")
        val out = base.resolve("target/test-generated/modeler-scala-value-powertype-only-cml")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates the value-side model artifacts")
        cozy.Cozy.main(Array("modeler-scala-value", input.toString, "--save", out.toString.toString))

        val countrycode = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/value/CountryCode.scala"
        )
        val addresstype = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/value/AddressType.scala"
        )
        Then("the generated values preserve the source model semantics")
        withClue(s"powertype file not found: $countrycode") {
        Files.exists(countrycode) shouldBe true
      }
        withClue(s"powertype file not found: $addresstype") {
        Files.exists(addresstype) shouldBe true
      }
      }

      "modeler-scala-value accepts statemachine-only .cml with literate narrative" in {
        Given("a literate top-level CML StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/statemachine-literate.cml")
        val out = base.resolve("target/test-generated/modeler-scala-value-statemachine-only-cml")
        val lifecycle = out.resolve(
          "target/scala-3.3.8/src_managed/main/scala/domain/statemachine/lifecycle.scala"
        )
        val domaincomponent = out.resolve(
          "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates the value-side StateMachine descriptor")
        cozy.Cozy.main(Array("modeler-scala-value", input.toString, "--save", out.toString.toString))

        Then("the literate source produces the event topology descriptor")
        withClue(s"statemachine file not found: $lifecycle") {
          Files.exists(lifecycle) shouldBe true
        }
        withClue(s"DomainComponent must not be generated in value mode: $domaincomponent") {
          Files.exists(domaincomponent) shouldBe false
        }
        val content = Files.readString(lifecycle)
        withClue(s"literate state-machine descriptor source must preserve topology: $content") {
          content should include ("object lifecycle {")
          content should include ("State(\"Draft\", Right(10))")
          content should include ("Transition(\"Draft\", Some(\"publish\"), \"Published\")")
          content should include ("def permits(from: String, event: String, to: String): Boolean =")
        }
      }

      "public StateMachine Scala generation preserves values, optional events, order, and escaping" in {
        Given("a top-level StateMachine with a string-valued state and ordered transitions")
        val statemachine = new MDomainStateMachine(
          Description.name("lifecycle"),
          MPackageRef("domain.statemachine")
        )
        val draft = MState.create(
          statemachine,
          "Draft",
          Left("quote\" slash\\ newline\nreturn\r tab\t")
        )
        val published = MState.create(statemachine, "Published", Right(2))
        val archived = MState.create(statemachine, "Archived", Right(3))
        statemachine.setStates(
          VectorMap(
            "Draft" -> draft,
            "Published" -> published,
            "Archived" -> archived
          )
        )
        val advance = MTransition(
          statemachine,
          Some(MEvent("advance")),
          None,
          draft,
          published,
          None
        )
        val eventless = MTransition(
          statemachine,
          None,
          None,
          draft,
          archived,
          None
        )
        val complete = MTransition(
          statemachine,
          Some(MEvent("complete")),
          None,
          draft,
          published,
          None
        )
        draft.transitions = List(advance, eventless, complete)

        When("the public StateMachine transformer and Scala generator emit source")
        val model = new StateMachineScalaModelTransformer()(
          (statemachine, ScalaModelTransformer.Purpose.Plain)
        ).take.collectFirst {
          case p: org.simplemodeling.SimpleModeler.generator.scala.model.SStateMachine => p
        }.getOrElse(fail("StateMachine transformer did not emit SStateMachine"))
        val generated = new Scala3StateMachineGenerator().generate(model).take
        val source = generated.slots.head.content

        Then("the generated source preserves every lossless StateMachine contract")
        generated.slots.head.path shouldBe "domain/statemachine/lifecycle.scala"
        source should include("package domain.statemachine")
        source should include(
          "State(\"Draft\", Left(\"quote\\\" slash\\\\ newline\\nreturn\\r tab\\t\"))"
        )
        source should include("Transition(\"Draft\", None, \"Archived\")")
        val advanceindex = source.indexOf("Transition(\"Draft\", Some(\"advance\"), \"Published\")")
        val eventlessindex = source.indexOf("Transition(\"Draft\", None, \"Archived\")")
        val completeindex = source.indexOf("Transition(\"Draft\", Some(\"complete\"), \"Published\")")
        advanceindex should be >= 0
        eventlessindex should be >= 0
        completeindex should be >= 0
        advanceindex should be < eventlessindex
        eventlessindex should be < completeindex
        source should include(
          """def permits(from: String, event: String, to: String): Boolean =
    transitions.exists { transition =>
      transition.from == from &&
        transition.event.contains(event) &&
        transition.to == to
    }"""
        )
      }

      "modeler-scala-value honors explicit ENTITY package without component" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-input/modeler-scala-value-entity-explicit-package.cml")
        val out = base.resolve("target/test-generated/modeler-scala-value-entity-explicit-package")
        delete_recursively(out)
        write_file(input,
        """# ENTITY
          |
          |## SimpleEntity
          |
          |### ATTRIBUTE
          |
          || name | type     | multiplicity |
          ||------|----------|--------------|
          || id   | entityid | 1            |
          || name | name     | 1            |
          |
          |## EditableInformation
          |
          |### FEATURES
          |
          |extends = ["SimpleEntity"]
          |package = org.goldenport.cncf.information
          |
          |### ATTRIBUTE
          |
          || name          | type   | multiplicity |
          ||---------------|--------|--------------|
          || informationId | string | 1            |
          |""".stripMargin)

        When("Cozy generates the value-side model artifacts")
        cozy.Cozy.main(Array("modeler-scala-value", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/org/goldenport/cncf/information/entity/EditableInformation.scala"
        )
        Then("the generated values preserve the source model semantics")
        withClue(s"entity file not found: $generated") {
        Files.exists(generated) shouldBe true
      }
        val content = Files.readString(generated)
        content should include ("extends org.simplemodeling.model.SimpleEntity with EntityPersistable")
      }

      "modeler-scala-value emits aggregate authorization hooks" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/aggregate-view-metadata.dox")
        val out = base.resolve("target/test-generated/modeler-scala-value-aggregate-hooks")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates the value-side model artifacts")
        cozy.Cozy.main(Array("modeler-scala-value", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/aggregate/Person.scala"
        )
        val content = Files.readString(generated)
        Then("the generated values preserve the source model semantics")
        content should include ("def renamePerson(input: Record)(using ctx: org.goldenport.cncf.context.ExecutionContext): Consequence[Person]")
        content should include ("""r <- aggregate_command_not_implemented[Person]("renamePerson")""")
        content should include ("def updatePerson(input: Record)(using ctx: org.goldenport.cncf.context.ExecutionContext): Consequence[Person]")
        content should include ("""_ <- if (r.id == id) Consequence.success(()) else Consequence.argumentInvalid(s"Aggregate id mismatch in updatePerson: expected ${id}, actual ${r.id}")""")
        content should include ("protected def aggregate_command_not_implemented[A](commandname: String): Consequence[A]")
        content should include ("def createPerson(input: Record)(using ctx: org.goldenport.cncf.context.ExecutionContext): Consequence[Person]")
        content should include ("r <- createC(input)")
        content should include ("def aggregate_create_not_implemented[A](commandname: String): Consequence[A]")
        content should not include ("authorizeAggregateCommand")
        content should not include ("authorizeAggregateCreate")
        content should not include ("AggregateAuthorization.authorizeCommand")
      }

      "kaleidox keeps VALUE and ENTITY in separate model domains with shared schema shape" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/value-entity-separation.dox")
        When("Cozy generates the value-side model artifacts")
        val model = KaleidoxModel.load(KaleidoxConfig.default.withoutLocation, input.toFile)

        val valuemodel = model.getValueModel.getOrElse {
        fail("ValueModel is missing")
      }
        val entitymodel = model.takeEntityModel

        val countrycode = valuemodel.get("CountryCode").getOrElse {
        fail("CountryCode in ValueModel is missing")
      }
        val person = entitymodel.get("Person").getOrElse {
        fail("Person in EntityModel is missing")
      }

        Then("the generated values preserve the source model semantics")
        countrycode.schema.columns.exists(_.name == "value") shouldBe true
        person.schema.columns.exists(_.name == "id") shouldBe true
        entitymodel.classes.contains("CountryCode") shouldBe false
        valuemodel.classes.contains("Person") shouldBe false
      }

      "modeler explain emits VALUE section roles and normalized targets" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/value-only-literate.dox")
        When("Cozy generates the value-side model artifacts")
        val model = KaleidoxModel.load(KaleidoxConfig.default.withoutLocation, input.toFile)
        val simplemodel = new cozy.modeler.Modeler().buildValueModel(model)
        val explain = new cozy.modeler.Modeler().explain(simplemodel)

        Then("the generated values preserve the source model semantics")
        explain.exists(e =>
        e.sectionPath == "VALUE/CountryCode" &&
        e.classifiedRole == "structural" &&
        e.normalizedTarget == "domain.value.CountryCode"
        ) shouldBe true
        explain.exists(e =>
        e.sectionPath == "VALUE/CountryCode/ATTRIBUTE/value" &&
        e.normalizedTarget == "domain.value.CountryCode.value"
        ) shouldBe true
      }

      "modeler explain covers production address.cml VALUE definitions" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get("/Users/asami/src/dev2026/simplemodeling-model").toAbsolutePath.normalize()
        val input = base.resolve("src/main/cozy/address.cml")
        When("Cozy generates the value-side model artifacts")
        val model = KaleidoxModel.load(KaleidoxConfig.default.withoutLocation, input.toFile)
        val simplemodel = new cozy.modeler.Modeler().buildValueModel(model)
        val explain = new cozy.modeler.Modeler().explain(simplemodel)

        Then("the generated values preserve the source model semantics")
        explain.exists(e =>
        e.sectionPath == "VALUE/Address" &&
        e.classifiedRole == "structural" &&
        e.normalizedTarget == "org.simplemodeling.model.value.Address"
        ) shouldBe true
        explain.exists(e =>
        e.sectionPath == "VALUE/CountryCode" &&
        e.normalizedTarget == "org.simplemodeling.model.value.CountryCode"
        ) shouldBe true
        explain.exists(e =>
        e.sectionPath == "VALUE/Address/ATTRIBUTE/addressCountry" &&
        e.normalizedTarget == "org.simplemodeling.model.value.Address.addressCountry"
        ) shouldBe true
      }

      "modeler help extracts production address.cml VALUE summaries" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get("/Users/asami/src/dev2026/simplemodeling-model").toAbsolutePath.normalize()
        val input = base.resolve("src/main/cozy/address.cml")
        When("Cozy generates the value-side model artifacts")
        val model = KaleidoxModel.load(KaleidoxConfig.default.withoutLocation, input.toFile)
        val help = new cozy.modeler.Modeler().help(model)

        Then("the generated values preserve the source model semantics")
        help.exists(e =>
        e.`type` == "value" &&
        e.name == "Address" &&
        e.summary.contains("Structured postal destination value")
        ) shouldBe true
        help.exists(e =>
        e.name == "CountryCode" &&
        e.summary.contains("Two-letter country code")
        ) shouldBe true
        help.exists(e =>
        e.name == "Address" &&
        e.details.get("description").exists(_.exists(_.contains("structured postal destination value")))
        ) shouldBe true
      }

      "modeler-scala accepts void operation input and output without value definitions" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-generated/modeler-scala-void-operation-types.dox")
        val out = base.resolve("target/test-generated/modeler-scala-void-operation-types-out")
        delete_recursively(out)
        write_file(input,
        """# COMPONENT
          |
          |## Domain
          |
          |### PACKAGE
          |
          |domain
          |
          |# SERVICE
          |
          |## Greeting
          |
          |### OPERATION
          |
          |#### ping
          |
          |##### TYPE
          |
          |COMMAND
          |
          |##### INPUT
          |
          |###### TYPE
          |
          |void
          |
          |##### OUTPUT
          |
          |###### TYPE
          |
          |void
          |""".stripMargin)

        When("Cozy generates the value-side model artifacts")
        val output = run_modeler_scala(input, out)
        Then("the generated values preserve the source model semantics")
        withClue(s"unexpected output: $output") {
        output should not include ("is not defined")
      }
        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        val content = Files.readString(generated)
        content should include ("""inputType = "void"""")
        content should include ("""outputType = "void"""")
      }

      "modeler-scala keeps generated aggregate/view/entity services when custom SERVICE coexists with VALUE definitions" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-generated/modeler-scala-service-entity-value-coexistence.dox")
        val out = base.resolve("target/test-generated/modeler-scala-service-entity-value-coexistence-out")
        delete_recursively(out)
        write_file(input,
        """# COMPONENT
          |
          |## StructuredKnowledge
          |
          |### PACKAGE
          |
          |org.simplemodeling.textus.mcprag
          |
          |# SERVICE
          |
          |## Knowledge
          |
          |### DESCRIPTION
          |
          |Knowledge groups source registration and explanation operations.
          |
          |### OPERATION
          |
          |#### registerSource
          |
          |##### TYPE
          |
          |COMMAND
          |
          |##### INPUT
          |###### TYPE
          |RegisterSourceRequest
          |
          |##### OUTPUT
          |###### TYPE
          |KnowledgeFragmentResponse
          |
          |#### explain
          |
          |##### TYPE
          |
          |QUERY
          |
          |##### INPUT
          |###### TYPE
          |ExplainKnowledgeRequest
          |
          |##### OUTPUT
          |###### TYPE
          |KnowledgeFragmentResponse
          |
          |# ENTITY
          |
          |## KnowledgeFragment
          |
          |### DESCRIPTION
          |
          |Primary semantic unit exposed to retrieval and explanation.
          |
          |### ATTRIBUTE
          |
          || name | type | multiplicity |
          ||------|------|--------------|
          || id | entityid | 1 |
          || text | string | 1 |
          || sourceType | string | 1 |
          || sourceId | string | 1 |
          |
          |# COMMAND
          |
          |## RegisterSourceRequest
          |
          |### ATTRIBUTE
          |
          || name | type | multiplicity |
          ||------|------|--------------|
          || sourceType | string | 1 |
          || payload | string | 1 |
          |
          |# QUERY
          |
          |## ExplainKnowledgeRequest
          |
          |### ATTRIBUTE
          |
          || name | type | multiplicity |
          ||------|------|--------------|
          || entityType | string | 1 |
          || id | string | 1 |
          |
          |## KnowledgeFragmentResponse
          |
          |### ATTRIBUTE
          |
          || name | type | multiplicity |
          ||------|------|--------------|
          || fragment | KnowledgeFragment | 1 |
          |
          |# VALUE
          |
          |## NamedValue
          |
          |### ATTRIBUTE
          |
          || name | type | multiplicity |
          ||------|------|--------------|
          || name | string | 1 |
          || value | string | 1 |
          |
          |## NamedValues
          |
          |### ATTRIBUTE
          |
          || name | type | multiplicity |
          ||------|------|--------------|
          || name | string | 1 |
          || values | string | * |
          |
          |""".stripMargin)

        When("Cozy generates the value-side model artifacts")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/org/simplemodeling/textus/mcprag/StructuredKnowledgeComponent.scala"
        )
        val content = Files.readString(generated)
        Then("the generated values preserve the source model semantics")
        content should include ("""object KnowledgeService extends ServiceDefinition {""")
        content should include ("""object AggregateService extends ServiceDefinition {""")
        content should include ("""object ViewService extends ServiceDefinition {""")
        content should include ("""object EntityService extends ServiceDefinition {""")
        content should include ("""override def aggregateDefinitions: Vector[org.goldenport.cncf.entity.aggregate.AggregateDefinition] = Vector(""")
        content should include ("""override def viewDefinitions: Vector[org.goldenport.cncf.entity.view.ViewDefinition] = Vector(""")
      }

      "modeler-scala-value is deterministic across repeated generation" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/address-literate.cml")
        val out1 = base.resolve("target/test-generated/modeler-scala-value-determinism-1")
        val out2 = base.resolve("target/test-generated/modeler-scala-value-determinism-2")
        delete_recursively(out1)
        delete_recursively(out2)
        Files.createDirectories(out1.getParent)
        Files.createDirectories(out2.getParent)

        When("Cozy generates the value-side model artifacts")
        cozy.Cozy.main(Array("modeler-scala-value", input.toString, "--save", out1.toString.toString))
        cozy.Cozy.main(Array("modeler-scala-value", input.toString, "--save", out2.toString.toString))

        val left = tree_snapshot(out1)
        val right = tree_snapshot(out2)
        Then("the generated values preserve the source model semantics")
        withClue(s"generated output differs between runs\nleft=$left\nright=$right") {
        left shouldBe right
      }
      }

      "modeler-scala-value emits Scaladoc from literate address.cml narrative" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/main/cozy/address.cml")
        val out = base.resolve("target/test-generated/modeler-scala-value-scaladoc")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates the value-side model artifacts")
        cozy.Cozy.main(Array("modeler-scala-value", input.toString, "--save", out.toString.toString))

        val buildsbt = out.resolve("build.sbt")
        Then("the generated values preserve the source model semantics")
        withClue(s"build.sbt must not be generated by default: $buildsbt") {
        Files.exists(buildsbt) shouldBe false
      }
      }

      "modeler-scala-value emits Scaladoc for powertype output" in {
        Given("a CML VALUE, Powertype, or StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/powertype-literate.cml")
        val out = base.resolve("target/test-generated/modeler-scala-value-powertype-scaladoc")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates the value-side model artifacts")
        cozy.Cozy.main(Array("modeler-scala-value", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/value/CountryCode.scala"
        )
        val content = Files.readString(generated)
        Then("the generated values preserve the source model semantics")
        content should include ("Country")
        content should include ("extends Powertype")
        content should include ("def fromDbValue")
      }

      "modeler-scala-value emits a statemachine topology descriptor" in {
        Given("a literate top-level CML StateMachine source model")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/statemachine-literate.cml")
        val out = base.resolve("target/test-generated/modeler-scala-value-statemachine-scaladoc")
        val generated = out.resolve(
          "target/scala-3.3.8/src_managed/main/scala/domain/statemachine/lifecycle.scala"
        )
        val domaincomponent = out.resolve(
          "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates the value-side StateMachine descriptor")
        cozy.Cozy.main(Array("modeler-scala-value", input.toString, "--save", out.toString.toString))

        Then("the generated source exposes immutable topology only")
        withClue(s"statemachine file not found: $generated") {
          Files.exists(generated) shouldBe true
        }
        withClue(s"DomainComponent must not be generated in value mode: $domaincomponent") {
          Files.exists(domaincomponent) shouldBe false
        }
        val content = Files.readString(generated)
        withClue(s"state-machine descriptor source must stay value-mode only: $content") {
          content should include ("final case class State(")
          content should include ("final case class Transition(")
          content should include ("val states: Vector[State]")
          content should include ("val transitions: Vector[Transition]")
          content should include ("def permits(from: String, event: String, to: String): Boolean =")
          content should not include ("DomainComponent")
          content should not include ("org.goldenport.cncf")
        }
      }

    }
  }
}
