package cozy.modeler

import java.io.ByteArrayOutputStream
import java.io.PrintStream
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Paths
import scala.collection.JavaConverters._
import org.scalatest.GivenWhenThen
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec
import org.goldenport.kaleidox.{Config => KaleidoxConfig, Model => KaleidoxModel}
import org.goldenport.record.v2.{CFormat, CMaxLength, CMinLength, CRegex}
import org.simplemodeling.model.{MNominalDataType, MStructuredDataType}
import play.api.libs.json.Json

/*
 * @since   Jun. 23, 2026
 * @version Aug.  7, 2026
 * @author  ASAMI, Tomoharu
 */
final class ModelerScalaGenerationSpec extends AnyWordSpec with Matchers with GivenWhenThen with ModelerSpecSupport {
  "CML modeler Scala generation" should {
    "generate component and entity source" which {
      "modeler-scala generates DomainComponent" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/test.dox")
        val out = base.resolve("target/test-generated/modeler-scala")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        val content = Files.readString(generated)
        Then("the generated Scala code preserves the model semantics")
        content should include ("object DomainComponent")
        val consequenceadaptations = "exec_from\\(".r.findAllMatchIn(content).toVector
        consequenceadaptations should have size 0
        content should not include "EntityConcurrencyMetadata"
        content should not include "snapshot.token"
        content should not include "cncfRevision"
        content should not include ("collectionId: EntityCollectionId = ???")
        content should include ("extends Component with CollectionTransitionRuleProvider")
        content should include ("override def stateMachineTransitionRules: Vector[CollectionTransitionRule[Any]] = Vector.empty")
        content should include ("override def stateMachineDefinitions: Vector[org.goldenport.cncf.statemachine.CmlStateMachineDefinition] = Vector.empty")
        content should include ("override def aggregateDefinitions: Vector[org.goldenport.cncf.entity.aggregate.AggregateDefinition] = Vector(")
        content should include ("override def viewDefinitions: Vector[org.goldenport.cncf.entity.view.ViewDefinition] = Vector(")
        withClue(s"build.sbt must not be generated by default: ${out.resolve("build.sbt")}") {
        Files.exists(out.resolve("build.sbt")) shouldBe false
      }
      }

      "modeler-scala expands attributes from SimpleEntity parent" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/simpleentity-parent.dox")
        val out = base.resolve("target/test-generated/modeler-scala-simpleentity-parent")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/Person.scala"
        )
        val notgeneratedsimpleentity = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/SimpleEntity.scala"
        )
        Then("the generated Scala code preserves the model semantics")
        withClue(s"SimpleEntity must not be generated: $notgeneratedsimpleentity") {
        Files.exists(notgeneratedsimpleentity) shouldBe false
      }
        val content = Files.readString(generated)
        content should include ("extends org.simplemodeling.model.SimpleEntity with EntityPersistable")
        content should include ("case class Person(override val id: EntityId")
        content should include ("nameAttributes: NameAttributes")
        content should include ("age: Option[Age]")
        content should include ("PROP_ID")
        content should include ("PROP_NAME_ATTRIBUTES")
        content should include ("PROP_AGE")
        content should include ("def toRecord(e: Person): Record = e.toRecord()")
        content should include ("override def toStoreRecord(e: Person): Record = e.toDataStore()")
        content should include (
          "override def fromStoreRecord(r: Record): Consequence[Person] = EntityStoreRecordProjection.project(r, _store_record_attributes).flatMap(createC)"
        )
        content should not include "EntityStoreDecodeContext"
        content should not include "EntityPersistent.restoreCollectionIdentity"
        content should include ("val sourcemap = source.asMap")
        content should not include ("val sourceMap = source.asMap")
        content should include (""""permission" -> _permission_json(securityAttributes.rights)""")
        content should include (""""ownerId" -> _to_external_value(securityAttributes.ownerId)""")
        content should include (""""createdAt" -> _to_external_value(lifecycleAttributes.createdAt)""")
        content should include (""""content" -> _to_external_value(contentAttributes.content)""")
        content should include (""""contentReferences" -> _to_external_value(contentAttributes.references)""")
        content should include ("""ContentAttributes.Builder(attrv.orElse(contentAttributes))""")
        content should include ("""_record_get_as_c[ContentBody](record, List("content"))""")
        content should include ("""copy(content = contentv)""")

        val generatedcreate = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/create/Person.scala"
        )
        withClue(s"generated file not found: $generatedcreate") {
        Files.exists(generatedcreate) shouldBe true
      }
        val createcontent = Files.readString(generatedcreate)
        createcontent should include ("case class Person(override val id: Option[EntityId]")
        createcontent should include ("nameAttributes: NameAttributes")
        createcontent should include ("age: Option[Age]")
        createcontent should include ("def toRecord(e: Person): Record = e.toRecord()")
        createcontent should include ("override def toStoreRecord(e: Person): Record = e.toDataStore()")
      }

      "modeler-scala generates SimpleEntity child without local attributes" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-generated/modeler-scala-simpleentity-empty-child-input.cml")
        val out = base.resolve("target/test-generated/modeler-scala-simpleentity-empty-child")
        delete_recursively(out)
        Files.createDirectories(input.getParent)
        Files.writeString(
        input,
        """# ENTITY
          |
          |## SimpleEntity
          |
          |### ATTRIBUTE
          |
          || name | type     | multiplicity |
          ||------+----------+--------------|
          || id   | entityid | 1            |
          || name | name     | 1            |
          |
          |## BlogPost
          |
          |### FEATURES
          |
          |extends = ["SimpleEntity"]
          |
          |### DESCRIPTION
          |
          |Uses only SimpleEntity standard fields.
          |""".stripMargin
        )

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/BlogPost.scala"
        )
        Then("the generated Scala code preserves the model semantics")
        withClue(s"generated file not found: $generated") {
        Files.exists(generated) shouldBe true
      }

        val content = Files.readString(generated)
        content should include ("case class BlogPost(override val id: EntityId")
        content should include ("nameAttributes: NameAttributes")
        content should not include ("slug:")
      }

      "modeler-scala emits exact scalar primary and reference identities without context repair" in {
        Given("a CML Entity with primary, optional, and repeated EntityId fields")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-generated/modeler-scala-entity-id-fields.cml")
        val out = base.resolve("target/test-generated/modeler-scala-entity-id-fields")
        delete_recursively(out)
        Files.createDirectories(input.getParent)
        Files.writeString(
          input,
          """# ENTITY
            |
            |## Facility
            |
            |### ATTRIBUTE
            |
            || name               | type     | multiplicity |
            ||--------------------+----------+--------------|
            || id                 | entityid | 1            |
            || primaryExhibitId   | entityid | ?            |
            || relatedExhibitIds  | entityid | *            |
            |""".stripMargin
        )

        When("Cozy generates the Entity persistence source")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString))
        val generated = out.resolve(
          "target/scala-3.3.8/src_managed/main/scala/domain/entity/Facility.scala"
        )
        val content = Files.readString(generated)

        Then("the generated source uses scalar EntityId fields without selected-owner repair")
        content should include("id: EntityId")
        content should include("primaryExhibitId: Option[EntityId]")
        content should include("relatedExhibitIds: Vector[EntityId]")
        content should include("\"primaryExhibitId\" -> _to_data_store_value(primaryExhibitId)")
        content should include("\"relatedExhibitIds\" -> _to_data_store_value(relatedExhibitIds)")
        content should include(
          "_record_get_as_c[EntityId](record, INPUT_KEYS_PRIMARY_EXHIBIT_ID)"
        )
        content should include(
          "_record_get_vector_as_c[org.simplemodeling.model.datatype.EntityId](record, INPUT_KEYS_RELATED_EXHIBIT_IDS)"
        )
        content should not include "EntityStoreDecodeContext"
        content should not include "EntityPersistent.restoreCollectionIdentity"
      }

      "modeler-scala generates a typed component API proxy and socket set" in {
        Given("a CML component that provides and consumes a component-specific SPI API")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/component-api-contract.cml")
        val out = base.resolve("target/test-generated/modeler-scala-component-api-contract")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates the Scala component source")
        cozy.Cozy.main(Array(
          "modeler-scala",
          input.toString,
          "--save",
          out.toString,
          "--component-namespace",
          "org.example.textus",
          "--component-id",
          "ComponentApiContract",
          "--component-version",
          "0.1.0-SNAPSHOT"
        ))

        val generated = out.resolve(
          "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        val content = Files.readString(generated)
        val api = Files.readString(out.resolve(
          "target/scala-3.3.8/src_managed/main/scala/domain/api/TextusScraperApi.scala"
        ))

        Then("the generated facade exposes typed operations through a binding-aware proxy")
        api should include ("trait TextusScraperApi")
        api should include ("request: domain.value.ScrapeRequest")
        api should include ("Consequence[domain.value.ScrapeResponse]")
        api should include ("def scrape(request: domain.value.ScrapeRequest)")
        api should include ("extends SpiBoundProvider[TextusScraperApi]")
        api should include ("extends TextusScraperApi with SpiSelectionAware[TextusScraperApi]")
        api should include ("binding.withSelection(selector, basis)")
        api should include ("binding.invoke(SpiOperationSelector(\"Scrape\", Some(\"Scraping\"))")

        And("the same contract supplies single and set sockets to consuming components")
        api should include ("final class Socket(")
        api should include ("final class SocketSet(")
        content should include ("new domain.api.TextusScraperApi.SocketSet(\"Scrapers\", true)")
        content should include ("protected final def scrapers(")
        content should include ("private val _scrapers_component_api_socket")
        content should include ("new domain.api.TextusScraperApi.Socket(\"PrimaryScraper\", true)")
        content should include ("protected final def primary_scraper: domain.api.TextusScraperApi")
        content should include ("new domain.api.TextusScraperApi.Socket(\"OptionalScraper\", false)")
        content should include ("protected final def optional_scraper: Option[domain.api.TextusScraperApi]")

        And("the generated descriptor records provided and required API metadata")
        val descriptor = Json.parse(Files.readString(out.resolve("target/cozy/component-api-descriptor.json")))
        (descriptor \ "schemaVersion").as[String] shouldBe "cncf.component-api.v2"
        (descriptor \ "component" \ "namespace").as[String] shouldBe "org.example.textus"
        (descriptor \ "component" \ "id").as[String] shouldBe "ComponentApiContract"
        (descriptor \ "component" \ "version").as[String] shouldBe "0.1.0-SNAPSHOT"
        val provided = (descriptor \ "provided").as[Vector[play.api.libs.json.JsObject]].head
        (provided \ "contract").as[String] shouldBe "Domain.Scraping"
        (provided \ "apiClass").as[String] shouldBe "domain.api.TextusScraperApi"
        (provided \ "version").as[String] shouldBe "0.1.0-SNAPSHOT"
        (provided \ "artifactPath").as[String] shouldBe "spi/textus-component-api-contract-api.jar"
        (provided \ "abiHash").as[String] should startWith("sha256:")
        (provided \ "publicTypes").as[Vector[play.api.libs.json.JsObject]].map(x => (x \ "className").as[String]) should contain allOf (
          "domain.api.TextusScraperApi",
          "domain.api.TextusScraperApi$Proxy",
          "domain.api.TextusScraperApi$Socket",
          "domain.api.TextusScraperApi$SocketSet",
          "domain.value.ScrapeRequest",
          "domain.value.ScrapeResponse"
        )
        val required = (descriptor \ "required").as[Vector[play.api.libs.json.JsObject]]
        required.map(x => ((x \ "service").as[String], (x \ "multiplicity").as[String], (x \ "required").as[Boolean])) should contain allOf (
          (("Scrapers", "*", true)),
          (("PrimaryScraper", "1", true)),
          (("OptionalScraper", "?", false))
        )
      }

      "modeler-scala carries derived entity attributes as schema-visible aliases" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/derived-attributes.cml")
        val out = base.resolve("target/test-generated/modeler-scala-derived-attributes")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/Notice.scala"
        )
        val content = Files.readString(generated)
        Then("the generated Scala code preserves the model semantics")
        content should include ("case class Notice(override val id: EntityId")
        content should not include ("recipientName: Option[String], subject")
        content should not include ("recipientName: Option[String], body")
        content should not include ("body: String, authorId")
        content should include ("def subject: String = title")
        content should include ("def subject(locale: java.util.Locale): String = title(locale)")
        content should include ("def withSubject(value: String): Notice")
        content should include ("def body: Option[org.simplemodeling.model.value.ContentBody] = content")
        content should not include ("def body(locale: java.util.Locale)")
        content should include ("def withBody(value: String): Notice")
        content should include ("def authorId: String = ownerId")
        content should include ("def withAuthorId(value: String): Notice")
        content should include ("org.simplemodeling.model.value.BaseContent.simple(\"subject\")")
        content should include ("org.simplemodeling.model.value.BaseContent.simple(\"body\")")
        content should include ("org.simplemodeling.model.value.BaseContent.simple(\"authorId\")")
        content should include ("""_record_get_as_c[String](record, List("nameAttributes.title", "name_attributes.title") ++ List("title", "subject"))""")
        content should include ("""_record_get_as_c[ContentBody](record, List("content", "body"))""")
        content should include ("""_record_with_derived_target_aliases(record, "ownerId", List("ownerId", "authorId"))""")
        content should include ("""val securityrecord = _record_with_derived_target_aliases(record, "ownerId", List("ownerId", "authorId"))""")
        content should not include ("val securityRecord =")

        val generatedquery = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/query/Notice.scala"
        )
        withClue(s"generated file not found: $generatedquery") {
        Files.exists(generatedquery) shouldBe true
      }
        val querycontent = Files.readString(generatedquery)
        querycontent should not include ("def subject: String = title")
        querycontent should not include (""""subject" -> _to_external_value(subject)""")
        querycontent should not include ("def authorId: String = ownerId")
        querycontent should not include (""""authorId" -> _to_external_value(authorId)""")
        querycontent should include ("val schema: org.goldenport.schema.Schema = domain.entity.Notice.schema")
      }

      "modeler-scala propagates CML web metadata into entity Schema columns" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/web-attribute-metadata.cml")
        val out = base.resolve("target/test-generated/modeler-scala-web-attribute-metadata")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/Notice.scala"
        )
        val generatedcreate = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/create/Notice.scala"
        )
        val generatedupdate = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/update/Notice.scala"
        )
        val content = Files.readString(generated)
        val createcontent = Files.readString(generatedcreate)
        val updatecontent = Files.readString(generatedupdate)

        Then("the generated Scala code preserves the model semantics")
        content should include ("""baseContent = org.simplemodeling.model.value.BaseContent.simple("senderName")""")
        content should include ("""label = Some(org.goldenport.datatype.I18nLabel("Sender"))""")
        content should include ("""placeholder = Some("Your name")""")
        content should include ("""help = Some("Name displayed as the poster.")""")
        content should include ("""validation = org.goldenport.schema.WebValidationHints(minLength = Some(1))""")
        content should include ("""label = Some(org.goldenport.datatype.I18nLabel("Recipient"))""")
        content should include ("""placeholder = Some("Recipient name")""")
        content should include ("""help = Some("Name used by recipients to find notices.")""")
        content should include ("""baseContent = org.simplemodeling.model.value.BaseContent.simple("title")""")
        content should include ("""label = Some(org.goldenport.datatype.I18nLabel("Title"))""")
        content should include ("""placeholder = Some("Short title")""")
        content should include ("""validation = org.goldenport.schema.WebValidationHints(minLength = Some(1), maxLength = Some(80), pattern = Some("^[A-Za-z0-9 ]+$"))""")
        content should include ("""baseContent = org.simplemodeling.model.value.BaseContent.simple("content")""")
        content should include ("""label = Some(org.goldenport.datatype.I18nLabel("Content"))""")
        content should include ("""web = org.goldenport.schema.WebColumn(controlType = Some("textarea"), required = Some(true), placeholder = Some("Notice content"), help = Some("Main notice text."), validation = org.goldenport.schema.WebValidationHints(minLength = Some(1)))""")
        createcontent should include ("private def _record_get_as_context_c[A](")
        createcontent should include ("record.getAsContextC[A](key)")
        createcontent should include ("def buildCWithExecutionContext(record: Record)(using ctx: org.goldenport.cncf.context.ExecutionContext)")
        createcontent should include ("_record_get_as_context_c(record, keys)(using vr, ctx)")
        content should include (
          """require(_text_constraint_values(senderName).forall(_.length >= 1), "senderName must have length >= 1")"""
        )
        content should include (
          """require(_text_constraint_values(nameAttributes.title).forall(_.length <= 80), "title entries must have length <= 80")"""
        )
        content should include (
          """require(_text_constraint_values(nameAttributes.title).forall(_.matches("^[A-Za-z0-9 ]+$")), "title entries must match ^[A-Za-z0-9 ]+$")"""
        )
        content should include (
          """require(_text_constraint_values(descriptiveAttributes.summary).forall(_.length >= 2), "summary entries must have length >= 2")"""
        )
        content should include (
          """require(_text_constraint_values(descriptiveAttributes.summary).forall(_.length <= 160), "summary entries must have length <= 160")"""
        )
        createcontent should include (
          """require(_text_constraint_values(nameAttributes.title).forall(_.length <= 80), "title entries must have length <= 80")"""
        )
        createcontent should include (
          """require(_text_constraint_values(descriptiveAttributes.summary).forall(_.length <= 160), "summary entries must have length <= 160")"""
        )
        updatecontent should include (
          "case x: org.simplemodeling.model.directive.Update[?] => x.fold(Vector.empty, _text_constraint_values, Vector.empty)"
        )
        updatecontent should include (
          """require(_text_constraint_values(nameAttributes.title).forall(_.length <= 80), "title entries must have length <= 80")"""
        )
        updatecontent should include (
          """require(_text_constraint_values(descriptiveAttributes.summary).forall(_.length <= 160), "summary entries must have length <= 160")"""
        )
      }

      "modeler-scala preserves repeated powertype metadata for entity update record operations" in {
        Given("a CML source model with a repeated powertype entity attribute")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-generated/modeler-scala-update-record-repeated-powertype.cml")
        val out = base.resolve("target/test-generated/modeler-scala-update-record-repeated-powertype")
        delete_recursively(out)
        write_file(input,
        """# COMPONENT
          |
          |## Domain
          |
          |### PACKAGE
          |
          |domain
          |
          |# ENTITY
          |
          |## Facility
          |
          |### ATTRIBUTE
          |
          || name          | type        | multiplicity |
          ||---------------+-------------+--------------|
          || id            | entityid    | 1            |
          || name          | name        | 1            |
          || description   | string      | ?            |
          || fetch_methods | FetchMethod | *            |
          |
          |# POWERTYPE
          |
          |## FetchMethod
          |
          |package = domain.value
          |
          || name            | label           |
          ||-----------------+-----------------|
          || official_driver | Official Driver |
          || museum_or_jp    | Museum.or.jp    |
          || ai_web_tools    | AI Web Tools    |
          |""".stripMargin)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        Then("the generated update-record operation metadata preserves the entity attribute contract")
        withClue(s"generated file not found: $generated") {
        Files.exists(generated) shouldBe true
      }
        val content = Files.readString(generated)
        content should include ("object UpdateFacilityRecordOperation extends OperationDefinition")
        content should include ("content = org.goldenport.value.BaseContent.simple(\"id\")")
        content should include ("multiplicity = org.goldenport.schema.Multiplicity.One")
        content should include ("content = org.goldenport.value.BaseContent.simple(\"name\")")
        content should include ("multiplicity = org.goldenport.schema.Multiplicity.ZeroOne")
        content should include ("content = org.goldenport.value.BaseContent.simple(\"fetch_methods\")")
        content should include ("datatype = org.goldenport.schema.DataType.Named(\"fetchmethod\")")
        content should include ("multiplicity = org.goldenport.schema.Multiplicity.ZeroMore")
        content should include (
          "CmlOperationField(name = \"name\", datatype = \"Name\", multiplicity = \"?\", validation = org.goldenport.schema.WebValidationHints(minLength = Some(1), maxLength = Some(256)), update = Some(org.goldenport.cncf.operation.CmlOperationUpdateField(sourceMultiplicity = \"1\", nullAllowed = false)))"
        )
        content should include (
          "CmlOperationField(name = \"description\", datatype = \"string\", multiplicity = \"?\", update = Some(org.goldenport.cncf.operation.CmlOperationUpdateField(sourceMultiplicity = \"?\", nullAllowed = true)))"
        )
        content should include (
          "CmlOperationField(name = \"fetch_methods\", datatype = \"FetchMethod\", multiplicity = \"*\", update = Some(org.goldenport.cncf.operation.CmlOperationUpdateField(sourceMultiplicity = \"*\", nullAllowed = false)))"
        )
        val update = out.resolve(
          "target/scala-3.3.8/src_managed/main/scala/domain/entity/update/Facility.scala"
        )
        val updatecontent = Files.readString(update)
        updatecontent should include ("private def _record_get_update_set_null[A]")
        updatecontent should include (
          "_record_get_update_set_null[String](record, INPUT_KEYS_DESCRIPTION) match"
        )
        updatecontent should include (
          "case _: org.simplemodeling.model.directive.Update.SetNull.type => org.simplemodeling.model.directive.Update.setNull[A]"
        )
      }

      "modeler-scala generates toDataStore with db column names" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/db-column-options.dox")
        val out = base.resolve("target/test-generated/modeler-scala-db-column-options")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/Person.scala"
        )
        val content = Files.readString(generated)
        Then("the generated Scala code preserves the model semantics")
        content should include ("def toRecord(): Record")
        content should include ("\"id\" -> _to_external_value(id)")
        content should include ("\"displayName\" -> _to_external_value(displayName)")
        content should include ("def toDataStore(): Record")
        content should include ("\"person_id\" -> _to_data_store_value(id)")
        content should include ("\"person_display_name\" -> _to_data_store_value(displayName)")
        content should include ("\"age\" -> _to_data_store_value(age)")
        content should include ("\"body\" -> _to_data_store_value(body)")
        content should include (
          """EntityStoreAttribute.scalarString("displayName", "person_display_name")"""
        )
        content should include ("INPUT_KEYS_DISPLAY_NAME")
        content should include ("\"display_name_ext\"")
        content should include ("\"displayName\"")
        content should not include ("\"display_name\"")
        content should include ("def schema(): Schema")
        content should include ("val schema: org.goldenport.schema.Schema = org.goldenport.schema.Schema(")
        content should include ("org.simplemodeling.model.value.BaseContent.simple(\"displayName\")")
        content should include ("""label = Some(org.goldenport.datatype.I18nLabel("Display Name"))""")
        content should include ("""label = Some(org.goldenport.datatype.I18nLabel("Body"))""")
        content should include ("""web = org.goldenport.schema.WebColumn(required = Some(true))""")
        content should include ("""web = org.goldenport.schema.WebColumn(controlType = Some("textarea"), required = Some(false), validation = org.goldenport.schema.WebValidationHints(minLength = Some(1), maxLength = Some(8192)))""")

        val generatedcreate = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/create/Person.scala"
        )
        withClue(s"generated file not found: $generatedcreate") {
        Files.exists(generatedcreate) shouldBe true
      }
        val createcontent = Files.readString(generatedcreate)
        createcontent should include ("val schema: org.goldenport.schema.Schema = domain.entity.Person.schema")

        val generatedquery = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/query/Person.scala"
        )
        withClue(s"generated file not found: $generatedquery") {
        Files.exists(generatedquery) shouldBe true
      }
        val querycontent = Files.readString(generatedquery)
        querycontent should include ("val schema: org.goldenport.schema.Schema = domain.entity.Person.schema")

        val generatedupdate = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/update/Person.scala"
        )
        withClue(s"generated file not found: $generatedupdate") {
        Files.exists(generatedupdate) shouldBe true
      }
        val updatecontent = Files.readString(generatedupdate)
        updatecontent should include ("val schema: org.goldenport.schema.Schema = domain.entity.Person.schema")
      }

      "modeler-scala preserves structural state-machine and powertype persistence semantics" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/statemachine-cml.dox")
        val out = base.resolve("target/test-generated/modeler-scala-statemachine-cml")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        val entitygenerated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/entity/Person.scala"
        )
        val statusgenerated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/PersonStatus.scala"
        )
        val content = Files.readString(generated)
        val entitycontent = Files.readString(entitygenerated)
        val statuscontent = Files.readString(statusgenerated)
        Then("the generated Scala code preserves the model semantics")
        content should include ("override def stateMachineTransitionRules: Vector[CollectionTransitionRule[Any]] = Vector(")
        content should include ("override def stateMachineDefinitions: Vector[org.goldenport.cncf.statemachine.CmlStateMachineDefinition] = Vector(")
        content should include ("name = \"lifecycle\"")
        content should include ("states = Vector(\"Draft\", \"Published\")")
        content should include ("events = Vector(\"publish\")")
        content should include ("eventName = \"publish\"")
        content should include ("machineName = Some(\"lifecycle\")")
        content should include ("stateFieldName = Some(\"status\")")
        content should include ("fromState = Some(\"Draft\")")
        content should include ("fromStateValue = Some(1)")
        content should include ("toState = Some(\"Published\")")
        content should include ("toStateValue = Some(2)")
        content should include ("guard = Some(StateMachineRuleBuilder.guardExpression[Any](\"event.amount > 0\")")
        content should include ("StateMachineRuleBuilder.updateRule[Any](")
        entitycontent should not include ("lifecycle: PersonLifecycle")
        entitycontent should include ("\"status\" -> _to_data_store_value(status)")
        entitycontent should include ("case m: org.simplemodeling.model.powertype.Powertype => m.dbValue.getOrElse(m.value)")
        statuscontent should include ("def toDataStore(): String")
        statuscontent should include ("case n: Int => fromDbValue(n)")
      }

      "modeler-scala maps identifier guard to guardRef" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/statemachine-cml-guard-ref.dox")
        val out = base.resolve("target/test-generated/modeler-scala-statemachine-cml-guard-ref")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        val content = Files.readString(generated)
        Then("the generated Scala code preserves the model semantics")
        content should include ("eventName = \"publish\"")
        content should include ("guard = Some(StateMachineRuleBuilder.guardRef[Any](\"paymentConfirmed\", stateMachineGuardResolver))")
      }

      "modeler-scala emits deterministic declaration order for mixed guards" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/statemachine-cml-guard-composite-order.dox")
        val out = base.resolve("target/test-generated/modeler-scala-statemachine-cml-guard-composite-order")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        val content = Files.readString(generated)
        Then("the generated Scala code preserves the model semantics")
        content should include ("eventName = \"submit\"")
        content should include ("eventName = \"publish\"")
        content should include ("eventName = \"approve\"")
        content should include ("eventName = \"reject\"")
        content should include ("guard = Some(StateMachineRuleBuilder.guardRef[Any](\"paymentConfirmed\", stateMachineGuardResolver))")
        content should include ("guard = Some(StateMachineRuleBuilder.guardExpression[Any](\"event.amount > 0 && reviewerApproved\")")
        content should include ("guard = Some(StateMachineRuleBuilder.guardExpression[Any](\"reviewerRejected || event.reasonPresent\")")
        content should include ("declarationOrder = 0")
        content should include ("declarationOrder = 1")
        content should include ("declarationOrder = 2")
        content should include ("declarationOrder = 3")
        count_token(content, "priority = 0") >= 4 shouldBe true
      }

    }

    "project datatypes and built-in values" which {
      "modeler-scala projects plain datatypes as constrained nominal scalars" in {
        Given("an ArtScene-like CML model with constrained nominal scalars and record values")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-generated/artscene-datastore-shape.cml")
        val out = base.resolve("target/test-generated/artscene-datastore-shape-out")
        delete_recursively(out)
        write_file(input,
        """# COMPONENT
          |
          |## ArtSceneSample
          |
          |### PACKAGE
          |
          |domain
          |
          |# ENTITY
          |
          |## Exhibition
          |
          |### ATTRIBUTE
          |
          || name             | type             | multiplicity |
          ||------------------+------------------+--------------|
          || title            | ExhibitionTitle  | 1            |
          || periodEnd        | ExhibitionDate   | 1            |
          || fetchSource      | FetchSource      | 1            |
          || sourceConfidence | SourceConfidence | ?            |
          || catalogLabel     | CatalogLabel     | 1            |
          || catalogPriority  | CatalogPriority  | 1            |
          || displayPeriod    | DisplayPeriod    | 1            |
          || publishedOn      | localdate        | 1            |
          |
          |# DATATYPE
          |
          |## ExhibitionDate
          |
          |### ATTRIBUTE
          |
          || name  | type   | multiplicity |
          ||-------+--------+--------------|
          || value | string | 1            |
          |
          |## ExhibitionTitle
          |
          |### ATTRIBUTE
          |
          || name  | type   | multiplicity | min-length | max-length | pattern       |
          ||-------+--------+--------------+------------+------------+---------------|
          || value | string | 1            | 3          | 80         | ^item.+$      |
          |
          |## FetchSource
          |
          |### ATTRIBUTE
          |
          || name  | type   | multiplicity |
          ||-------+--------+--------------|
          || value | string | 1            |
          |
          |## SourceConfidence
          |
          |### ATTRIBUTE
          |
          || name  | type | multiplicity |
          ||-------+------+--------------|
          || value | int  | 1            |
          |
          |## DisplayPeriod
          |
          |### ATTRIBUTE
          |
          || name  | type   | multiplicity |
          ||-------+--------+--------------|
          || start | string | 1            |
          || end   | string | 1            |
          |
          |# VALUE
          |
          |## CatalogLabel
          |
          |### ATTRIBUTE
          |
          || name  | type   | multiplicity |
          ||-------+--------+--------------|
          || value | string | 1            |
          |
          |## CatalogPriority
          |
          |### ATTRIBUTE
          |
          || name  | type | multiplicity |
          ||-------+------+--------------|
          || value | int  | 1            |
          |""".stripMargin)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString))

        val model = KaleidoxModel.parseWitoutLocation(KaleidoxConfig.log.debug, Files.readString(input))
        val simplemodel = Modeler.ModelBuilder(model).build()
        val exhibitiontitlemodel = simplemodel.elements.collectFirst {
          case m: MNominalDataType if m.name == "ExhibitionTitle" => m
        }.get
        Then("the CML AST projects the underlying type and constraints into a nominal scalar model")
        exhibitiontitlemodel.packageName shouldBe "domain.datatype"
        exhibitiontitlemodel.datatype shouldBe org.goldenport.record.v2.XString
        exhibitiontitlemodel.constraints.map(_.name) should contain allOf ("min_length", "max_length", "pattern")
        exhibitiontitlemodel.constraints.map(_.value) should contain allOf (3, 80, "^item.+$")

        val nominaldatatypes = Vector(
          "ExhibitionDate" -> "String",
          "ExhibitionTitle" -> "String",
          "FetchSource" -> "String",
          "SourceConfidence" -> "Int"
        )
        nominaldatatypes.foreach { case (name, underlying) =>
          val source = out.resolve(s"target/scala-3.3.8/src_managed/main/scala/domain/datatype/$name.scala")
          val content = Files.readString(source)
          And(s"the plain datatype $name is generated as a scalar nominal type")
          content should include ("package domain.datatype")
          content should include (s"case class $name(value: $underlying")
          content should include ("extends org.simplemodeling.model.value.NominalScalar")
          content should include (s"def toDataStore(): $underlying")
          content should include (s"ValueReader[$name]")
          content should include (s"given Codec[$name] = Codec.from(")
          content should not include ("derives Codec.AsObject")
        }

        val exhibitiontitle = out.resolve("target/scala-3.3.8/src_managed/main/scala/domain/datatype/ExhibitionTitle.scala")
        val exhibitiontitlecontent = Files.readString(exhibitiontitle)
        And("nominal scalar construction enforces the declared text constraints")
        exhibitiontitlecontent should include ("_text_constraint_values(value).forall(_.length >= 3)")
        exhibitiontitlecontent should include ("_text_constraint_values(value).forall(_.length <= 80)")
        exhibitiontitlecontent should include ("_text_constraint_values(value).forall(_.matches(\"^item.+$\"))")

        val cataloglabel = out.resolve("target/scala-3.3.8/src_managed/main/scala/domain/value/CatalogLabel.scala")
        val cataloglabelcontent = Files.readString(cataloglabel)
        And("single-field values keep external records but expose scalar datastore values")
        cataloglabelcontent should include ("def toRecord(): Record")
        cataloglabelcontent should include ("\"value\" -> _to_external_value(value)")
        cataloglabelcontent should include ("def toDataStore(): String")
        cataloglabelcontent should not include ("def toDataStore(): Record")
        And("single-field value readers restore typed, record, and scalar datastore forms")
        cataloglabelcontent should include ("case m: CatalogLabel => Consequence.success(m)")
        cataloglabelcontent should include (
          "case m: Record if INPUT_KEYS_VALUE.exists(key => m.getAny(key).isDefined) => createC(m)"
        )
        cataloglabelcontent should include (
          "case m: Record => Consequence.valueInvalid(m, org.goldenport.schema.XString)"
        )
        cataloglabelcontent should not include ("case m: Record => createC(m.toJsonString)")
        cataloglabelcontent should include (
          "case other => summon[org.goldenport.convert.ValueReader[String]].readC(other).flatMap(value => createC(value).recoverWith(conclusion => Consequence.valueInvalid(conclusion.displayMessage)))"
        )

        val catalogpriority = out.resolve("target/scala-3.3.8/src_managed/main/scala/domain/value/CatalogPriority.scala")
        val catalogprioritycontent = Files.readString(catalogpriority)
        And("numeric single-field values delegate malformed primitive input to the integer reader")
        catalogprioritycontent should include ("def toDataStore(): Int")
        catalogprioritycontent should include (
          "case other => summon[org.goldenport.convert.ValueReader[Int]].readC(other).flatMap(value => createC(value).recoverWith(conclusion => Consequence.valueInvalid(conclusion.displayMessage)))"
        )

        val displayperiod = out.resolve("target/scala-3.3.8/src_managed/main/scala/domain/datatype/DisplayPeriod.scala")
        val displayperiodcontent = Files.readString(displayperiod)
        And("complex datatypes are generated as structured datatype classes")
        displayperiodcontent should include ("package domain.datatype")
        displayperiodcontent should include ("case class DisplayPeriod(")
        displayperiodcontent should include ("start: String")
        displayperiodcontent should include ("end: String")
        displayperiodcontent should include ("def toRecord(): Record")
        displayperiodcontent should include ("def toDataStore(): Record")
        displayperiodcontent should include ("\"start\" -> _to_data_store_value(start)")
        displayperiodcontent should include ("\"end\" -> _to_data_store_value(end)")

        val exhibition = out.resolve("target/scala-3.3.8/src_managed/main/scala/domain/entity/Exhibition.scala")
        val exhibitioncontent = Files.readString(exhibition)
        And("entity fields retain nominal scalar identity")
        exhibitioncontent should include ("title: ExhibitionTitle")
        exhibitioncontent should include ("periodEnd: ExhibitionDate")
        exhibitioncontent should include ("fetchSource: FetchSource")
        exhibitioncontent should include ("sourceConfidence: Option[SourceConfidence]")
        exhibitioncontent should include ("catalogPriority: CatalogPriority")
        exhibitioncontent should include ("displayPeriod: DisplayPeriod")
        And("referencing fields project nominal scalar identity and constraints into generated schema")
        exhibitioncontent should include ("datatype = org.goldenport.schema.DataType.Named(\"ExhibitionTitle\")")
        exhibitioncontent should include ("validation = org.goldenport.schema.WebValidationHints(minLength = Some(3), maxLength = Some(80), pattern = Some(\"^item.+$\"))")
        And("entity datastore conversion delegates value objects and structured datatypes to datastore values")
        exhibitioncontent should include ("case m: domain.datatype.ExhibitionDate => m.toDataStore()")
        exhibitioncontent should include ("case m: domain.datatype.ExhibitionTitle => m.toDataStore()")
        exhibitioncontent should include ("case m: domain.datatype.FetchSource => m.toDataStore()")
        exhibitioncontent should include ("case m: domain.datatype.SourceConfidence => m.toDataStore()")
        exhibitioncontent should include ("case m: domain.value.CatalogLabel => m.toDataStore()")
        exhibitioncontent should include ("case m: domain.value.CatalogPriority => m.toDataStore()")
        exhibitioncontent should include ("case m: domain.datatype.DisplayPeriod => m.toDataStore()")
        exhibitioncontent should include ("case m: Option[?] => m.map(_to_data_store_value)")
        exhibitioncontent should include ("\"periodEnd\" -> _to_data_store_value(periodEnd)")
        exhibitioncontent should include ("\"fetchSource\" -> _to_data_store_value(fetchSource)")
        exhibitioncontent should include ("\"sourceConfidence\" -> _to_data_store_value(sourceConfidence)")
        exhibitioncontent should include ("\"catalogLabel\" -> _to_data_store_value(catalogLabel)")
        exhibitioncontent should include ("\"catalogPriority\" -> _to_data_store_value(catalogPriority)")
        exhibitioncontent should include ("\"displayPeriod\" -> _to_data_store_value(displayPeriod)")
        exhibitioncontent should include ("\"publishedOn\" -> _to_data_store_value(publishedOn)")
        And("generated persistence metadata distinguishes scalar String and structured fields")
        exhibitioncontent should include (
          """EntityStoreAttribute.scalarString("title", "title")"""
        )
        exhibitioncontent should include (
          """EntityStoreAttribute.scalarString("periodEnd", "periodEnd")"""
        )
        exhibitioncontent should include (
          """EntityStoreAttribute.scalarString("catalogLabel", "catalogLabel")"""
        )
        exhibitioncontent should not include (
          """EntityStoreAttribute.scalarString("sourceConfidence", "sourceConfidence")"""
        )
        exhibitioncontent should not include (
          """EntityStoreAttribute.scalarString("displayPeriod", "displayPeriod")"""
        )
        exhibitioncontent should include (
          "EntityStoreRecordProjection.project(r, _store_record_attributes).flatMap(createC)"
        )
      }

      "modeler-scala projects complex datatypes as structured datatype objects" in {
        Given("a CML model with a multi-attribute DATATYPE")
        val source =
        """# DATATYPE
          |
          |## DisplayPeriod
          |
          |### ATTRIBUTE
          |
          || name  | type   | multiplicity |
          ||-------+--------+--------------|
          || start | string | 1            |
          || end   | string | 1            |
          |""".stripMargin
        val model = KaleidoxModel.parseWitoutLocation(KaleidoxConfig.log.debug, source)

        When("Cozy projects the model into SimpleModeling classes")
        val simplemodel = Modeler.ModelBuilder(model).build()

        Then("the complex datatype remains a datatype-package model object")
        val datatype = simplemodel.elements.collectFirst {
          case m: MStructuredDataType if m.name == "DisplayPeriod" => m
        }.get
        datatype.packageName shouldBe "domain.datatype"
        datatype.attributes.map(_.name) shouldBe List("start", "end")
      }

      "modeler-scala recognizes filebundle as a builtin datatype" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-generated/filebundle-type.cml")
        val out = base.resolve("target/test-generated/filebundle-type-out")
        delete_recursively(out)
        write_file(input,
        """# COMPONENT
          |
          |## FileBundleSample
          |
          |### PACKAGE
          |
          |domain
          |
          |# ENTITY
          |
          |## ImportJob
          |
          |### ATTRIBUTE
          |
          || name | type   | multiplicity |
          ||------+--------+--------------|
          || name | string | 1            |
          |
          |# SERVICE
          |
          |## ImportService
          |
          |### OPERATION
          |
          |#### importBundle
          |
          |##### TYPE
          |
          |COMMAND
          |
          |##### INPUT
          |
          |###### TYPE
          |
          |ImportBundle
          |
          |##### OUTPUT
          |
          |###### TYPE
          |
          |ImportResult
          |
          |# VALUE
          |
          |## ImportBundle
          |
          |### EXTENDS
          |
          |CommandAction
          |
          |### ATTRIBUTE
          |
          || name | type       | multiplicity |
          ||------+------------+--------------|
          || tree | filebundle | 1            |
          |
          |## ImportResult
          |
          |### EXTENDS
          |
          |OperationResult
          |
          |### ATTRIBUTE
          |
          || name | type    | multiplicity |
          ||------+---------+--------------|
          || ok   | boolean | 1            |
          |""".stripMargin)

        When("Cozy generates Scala source from the model")
        val output = run_modeler_scala(input, out)
        Then("the generated Scala code preserves the model semantics")
        withClue(s"unexpected output: $output") {
        output should not include ("Unknown CML attribute type")
      }
        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/FileBundleSampleComponent.scala"
        )
        val content = Files.readString(generated)
        content should include ("""datatype = "filebundle"""")
      }

    }

    "project runtime metadata and operation contracts" which {
      "modeler-scala emits aggregate metadata into component definitions" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/aggregate-view-metadata.dox")
        val out = base.resolve("target/test-generated/modeler-scala-aggregate-view-metadata")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        val content = Files.readString(generated)
        Then("the generated Scala code preserves the model semantics")
        content should include ("""name = "person"""")
        content should include ("""entityName = "person"""")
        content should include ("""viewNames = Vector("summary", "detail")""")
        content should include ("""input = Map("input.name" -> "name")""")
        content should include ("""ViewQueryDefinition(name = "search_published""")
        content should include ("""poststatus == """)
        content should include ("""published""")
        content should include ("""sourceEvents = Vector("person.created", "person.updated")""")
        content should include ("""rebuildable = Some(true)""")
        content should include ("""AggregateMemberDefinition(""")
        content should include ("""name = "post"""")
        content should include ("""entityName = "post"""")
        content should include ("""joinFieldName = Some("personId")""")
        content should include ("""multiplicity = Some("*")""")
        content should include ("""AggregateCreateDefinition(""")
        content should include ("""name = "createPerson"""")
        content should include ("""initialState = Some("Active")""")
        content should include ("""implementation = Some("pattern:create")""")
        content should include ("""AggregateCommandDefinition(""")
        content should include ("""name = "updatePerson"""")
        content should include ("""events = Vector("person.updated")""")
        content should include ("""newState = Some("Active")""")
        content should include ("""name = "renamePerson"""")
        content should include ("""input = Map("input.name" -> "name")""")
        content should include ("""validations = Vector("name.nonEmpty")""")
        content should include ("""events = Vector("person.renamed")""")
        content should include ("""newState = Some("Active")""")
        content should include ("""implementation = Some("pattern:copy-update")""")
        content should include ("""AggregateStateDefinition(""")
        content should include ("""datatype = Some("entityid")""")
        content should include ("""AggregateInvariantDefinition(""")
        content should include ("""expression = Some("state.name.nonEmpty")""")
        content should include ("""r <- aggregate_create("person", "createPerson", domain.entity.aggregate.Person.createPerson(action.entity.toRecord())(using executionContext))""")
        content should include ("""id <- exec_from(Consequence.successOrRecordNotFound[EntityId]("id", action.request.toRecord))""")
        content should include ("""current <- aggregate_load[domain.entity.aggregate.Person](id)""")
        content should include ("""r <- aggregate_update("person", id, "updatePerson", current.updatePerson(action.entity.toRecord())(using executionContext))""")
        content should not include ("""aggregate_update("person", action.entity.id""")
        content should not include ("""aggregate_put_record("person", r.toRecord())""")
        content should not include ("collection.putRecord(r.toRecord())")
        content should not include ("""aggregate_authorize_instance("person", action.id, "read"""")
      }

      "modeler-scala emits eventReceptionDefinitions from Event section" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/event-metadata.dox")
        val out = base.resolve("target/test-generated/modeler-scala-event-metadata")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        val content = Files.readString(generated)
        Then("the generated Scala code preserves the model semantics")
        content should include ("def eventReceptionDefinitions: Vector[org.goldenport.cncf.event.CmlEventDefinition] = Vector(")
        content should include ("name = \"person.created\"")
        content should include ("category = org.goldenport.cncf.event.CmlEventCategory.ActionEvent")
        content should include ("kind = Some(\"created\")")
        content should include ("selectors = Map(\"source\" -> \"crm\")")
        content should include ("actionName = Some(\"person.sync\")")
        content should include ("priority = 1")
        content should include ("name = \"order.shipped\"")
        content should include ("category = org.goldenport.cncf.event.CmlEventCategory.NonActionEvent")
        content should include ("actionName = None")
      }

      "preserve entity authorization classification from CML to generated component descriptors" in {
        Given("a CML entity with usage, operation, and application-domain classification features")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-generated/modeler-entity-authorization-classification.dox")
        write_file(input,
        """# SCHEMA
          |
          |## SalesOrderSchema
          |
          |### ATTRIBUTE
          |
          || name | type   |
          ||------+--------|
          || id   | string |
          |
          |# ENTITY
          |
          |## SalesOrder
          |
          |### FEATURES
          |
          |schema = "SalesOrderSchema"
          |usageKind = "business-object"
          |operationKind = "resource"
          |applicationDomain = "business"
          |""".stripMargin
        )

        When("the literate CML model is parsed into the Kaleidox entity model")
        val model = KaleidoxModel.load(KaleidoxConfig.default.withoutLocation, input.toFile)
        val entity = model.takeEntityModel.get("SalesOrder").getOrElse {
        fail("SalesOrder in EntityModel is missing")
      }

        Then("the entity model keeps the classification values as entity semantics")
        entity.usageKind shouldBe Some("business-object")
        entity.operationKind shouldBe Some("resource")
        entity.applicationDomain shouldBe Some("business")

        val out = base.resolve("target/test-generated/modeler-scala-entity-authorization-classification")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("the same model is projected into generated Scala component code")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        Then("the generated component declares CNCF runtime descriptors for the entity")
        Files.exists(generated) shouldBe true
        val content = Files.readString(generated)
        content should include ("override def componentDescriptors: Vector[org.goldenport.cncf.component.ComponentDescriptor] = Vector(")
        content should include ("""entityName = "SalesOrder"""")
        content should include ("collectionId = domain.entity.SalesOrder.collectionId")

        And("the descriptor carries the same classification values into CNCF security/runtime metadata")
        content should include ("""usageKind = org.goldenport.cncf.security.EntityUsageKind.parse("business-object")""")
        content should include ("""operationKind = org.goldenport.cncf.security.EntityOperationKind.parse("resource")""")
        content should include ("""applicationDomain = org.goldenport.cncf.security.EntityApplicationDomain.parse("business")""")
      }

      "modeler-scala accepts non-canonical void with warning" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-generated/modeler-scala-noncanonical-void-operation-types.dox")
        val out = base.resolve("target/test-generated/modeler-scala-noncanonical-void-operation-types-out")
        delete_recursively(out)
        write_file(input,
        """# COMPONENT
          |
          |## Domain
          |
          |### PACKAGE
          |
          |domain
          |
          |# SERVICE
          |
          |## Greeting
          |
          |### OPERATION
          |
          |#### ping
          |
          |##### TYPE
          |
          |COMMAND
          |
          |##### INPUT
          |
          |###### TYPE
          |
          |Void
          |
          |##### OUTPUT
          |
          |###### TYPE
          |
          |VOID
          |""".stripMargin)

        When("Cozy generates Scala source from the model")
        val output = run_modeler_scala(input, out)
        Then("the generated Scala code preserves the model semantics")
        withClue(s"unexpected output: $output") {
        output should include ("Operation 'ping' uses 'Void'; use canonical 'void'.")
      }
        withClue(s"unexpected output: $output") {
        output should include ("Operation 'ping' uses 'VOID'; use canonical 'void'.")
      }
        withClue(s"unexpected output: $output") {
        output should not include ("is not defined")
      }
      }

      "modeler-scala emits AwsComponent S3 inline values with key long boolean and double fields" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-generated/modeler-scala-aws-s3-inline-values.dox")
        val out = base.resolve("target/test-generated/modeler-scala-aws-s3-inline-values-out")
        delete_recursively(out)
        write_file(input,
        """# COMPONENT
          |## AwsComponent
          |### PACKAGE
          |org.simplemodeling.textus.aws
          |# SERVICE
          |## S3
          |### OPERATION
          |#### putS3Object
          |##### TYPE
          |COMMAND
          |##### INPUT
          |PutS3Object
          |###### VALUE
          |####### PutS3Object
          |######## EXTENDS
          |CommandAction
          |######## ATTRIBUTE
          || name        | type   | multiplicity |
          ||-------------+--------+--------------|
          || bucketName  | string | 1            |
          || key         | string | 1            |
          || content     | string | 1            |
          || contentType | string | ?            |
          |##### OUTPUT
          |PutS3ObjectResult
          |###### VALUE
          |####### PutS3ObjectResult
          |######## EXTENDS
          |OperationResult
          |######## ATTRIBUTE
          || name       | type | multiplicity |
          ||------------+------+--------------|
          || bucketName | string | 1          |
          || key        | string | 1          |
          || sizeBytes  | long | ?            |
          |#### deleteS3Object
          |##### TYPE
          |COMMAND
          |##### INPUT
          |DeleteS3Object
          |###### VALUE
          |####### DeleteS3Object
          |######## EXTENDS
          |CommandAction
          |######## ATTRIBUTE
          || name       | type   | multiplicity |
          ||------------+--------+--------------|
          || bucketName | string | 1            |
          || key        | string | 1            |
          |##### OUTPUT
          |DeleteS3ObjectResult
          |###### VALUE
          |####### DeleteS3ObjectResult
          |######## EXTENDS
          |OperationResult
          |######## ATTRIBUTE
          || name       | type    | multiplicity |
          ||------------+---------+--------------|
          || bucketName | string  | 1            |
          || key        | string  | 1            |
          || deleted    | boolean | 1            |
          || confidence | double  | 1            |
          |# ENTITY
          |## S3Object
          |### ATTRIBUTE
          || name       | type     | multiplicity |
          ||------------+----------+--------------|
          || id         | entityid | 1            |
          || bucketName | string   | 1            |
          || key        | string   | 1            |
          || sizeBytes  | long     | ?            |
          |""".stripMargin)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val component = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/org/simplemodeling/textus/aws/AwsComponentComponent.scala"
        )
        val put = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/org/simplemodeling/textus/aws/value/PutS3Object.scala"
        )
        val deleteresult = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/org/simplemodeling/textus/aws/value/DeleteS3ObjectResult.scala"
        )
        Then("the generated Scala code preserves the model semantics")
        withClue(s"generated component not found: $component") {
        Files.exists(component) shouldBe true
      }
        withClue(s"generated input value not found: $put") {
        Files.exists(put) shouldBe true
      }
        withClue(s"generated output value not found: $deleteresult") {
        Files.exists(deleteresult) shouldBe true
      }
        val content = Files.readString(deleteresult)
        withClue(s"boolean field was not generated as Scala Boolean\n$content") {
        content should include ("deleted: Boolean")
      }
        withClue(s"boolean String builder did not use Consequence.toBoolean\n$content") {
        content should include ("Consequence.toBoolean")
      }
        withClue(s"double field was not generated as Scala Double\n$content") {
        content should include ("confidence: Double")
      }
        withClue(s"double String builder did not use Consequence.toDouble\n$content") {
        content should include ("Consequence.toDouble")
      }
      }

      "modeler-scala does not double-wrap optional entityid attributes in create models" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-generated/modeler-optional-entityid.dox")
        val out = base.resolve("target/test-generated/modeler-optional-entityid-out")
        delete_recursively(out)
        write_file(input,
        """# COMPONENT
          |
          |## BlogComponent
          |
          |### PACKAGE
          |
          |org.simplemodeling.textus.blog
          |
          |# ENTITY
          |
          |## BlogPost
          |
          |### FEATURES
          |
          |extends = ["SimpleEntity"]
          |
          |### ATTRIBUTE
          |
          || name           | type     | multiplicity |
          ||----------------+----------+--------------|
          || id             | entityid | 1            |
          || title          | string   | 1            |
          || primaryImageId | entityid | ?            |
          |
          |""".stripMargin
        )

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/org/simplemodeling/textus/blog/entity/create/BlogPost.scala"
        )
        val content = Files.readString(generated)
        Then("the generated Scala code preserves the model semantics")
        withClue(s"optional entityid was not generated as Option[EntityId]\n$content") {
        content should include ("primaryImageId: Option[EntityId]")
      }
        withClue(s"optional entityid was double-wrapped\n$content") {
        content should not include ("primaryImageId: Option[Option[EntityId]]")
      }
        withClue(s"builder overload should not use Option[Option[EntityId]]\n$content") {
        content should not include ("withPrimaryImageId(primaryImageId: Option[Option[EntityId]])")
      }
        withClue(s"record reader should read raw EntityId and let record lookup carry optionality\n$content") {
        content should include ("_record_get_as_c[EntityId](record, INPUT_KEYS_PRIMARY_IMAGE_ID)")
      }
      }

      "modeler-scala emits component/subsystem metadata records" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/component-subsystem-grammar.dox")
        val out = base.resolve("target/test-generated/modeler-scala-component-subsystem-grammar")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/PersonComponent.scala"
        )
        val content = Files.readString(generated)
        Then("the generated Scala code preserves the model semantics")
        content should include ("def componentDefinitionRecords: Vector[Record] = Vector(")
        content should include ("def subsystemDefinitionRecords: Vector[Record] = Vector(")
        content should include ("\"name\" -> \"person\"")
        content should include ("\"coordinates\" -> Vector(\"org.simplemodeling.car:person-service:0.1.0\")")
        content should include ("\"extension_bindings\" -> Record.data(")
        content should include ("\"transport\" -> \"grpc\"")
        content should include ("\"use_cases\" -> Vector(")
        content should include ("\"name\" -> \"provisional_onboarding\"")
        content should include ("\"actor\" -> \"EndUser\"")
        content should include ("\"name\" -> \"identity\"")
      }

      "modeler-scala preserves ArtScene actor and use-case models" in {
        Given("an ArtScene-like component with typed actors and a canonical use-case flow")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-generated/modeler-art-scene-use-case.dox")
        val out = base.resolve("target/test-generated/modeler-art-scene-use-case-out")
        delete_recursively(out)
        write_file(input,
        """# COMPONENT
          |
          |## ArtScene
          |
          |### PACKAGE
          |
          |org.simplemodeling.textus.artscene
          |
          |### USE CASE
          |
          |#### personal_planning
          |
          |##### ID
          |
          |UC-ART-001
          |
          |##### PRIMARY ACTOR
          |
          |ExhibitionVisitor
          |
          |##### SUPPORTING ACTOR
          |
          |TextusUserNotification, CatalogOperator
          |
          |##### GOAL
          |
          |Plan an exhibition visit.
          |
          |##### TRIGGER
          |
          |The visitor opens today's candidates.
          |
          |##### PRIORITY
          |
          |high
          |
          |##### STATUS
          |
          |approved
          |
          |##### MAIN FLOW
          |
          |###### daily_planning
          |
          |1. The visitor reviews today's candidates.
          |2. The system preserves the visit decision.
          |
          |# ACTOR
          |
          |## ExhibitionVisitor
          |
          |### KIND
          |
          |human
          |
          |### DESCRIPTION
          |
          |A person planning exhibition visits.
          |
          |## CatalogOperator
          |
          |### KIND
          |
          |human
          |
          |# ENTITY
          |
          |## Exhibition
          |
          |### ATTRIBUTE
          |
          || name | type   | multiplicity |
          ||------+--------+--------------|
          || id   | string | 1            |
          |""".stripMargin)

        When("Cozy generates the component contract")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString))

        Then("actor definitions and resolved use-case references remain structured metadata")
        val generated = out.resolve(
          "target/scala-3.3.8/src_managed/main/scala/org/simplemodeling/textus/artscene/ArtSceneComponent.scala"
        )
        val content = Files.readString(generated)
        content should include ("\"actors\" -> Vector(")
        content should include ("\"name\" -> \"ExhibitionVisitor\"")
        content should include ("\"id\" -> \"UC-ART-001\"")
        content should include ("\"trigger\" -> \"The visitor opens today's candidates.\"")
        content should include ("\"priority\" -> \"high\"")
        content should include ("\"status\" -> \"approved\"")
        content should include ("\"name\" -> \"ExhibitionVisitor\", \"role\" -> \"primary\", \"target_kind\" -> \"actor\"")
        content should include ("\"name\" -> \"TextusUserNotification\", \"role\" -> \"supporting\", \"target_kind\" -> \"external\"")
        content should include ("\"name\" -> \"CatalogOperator\", \"role\" -> \"supporting\", \"target_kind\" -> \"actor\"")
        content should include ("\"kind\" -> \"main\"")
      }

    }

    "project packages routing and relationships" which {
      "modeler-scala emits component in configured package" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/component-subsystem-component-package.dox")
        val out = base.resolve("target/test-generated/modeler-scala-component-subsystem-component-package")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/textus/user/account/DomainComponent.scala"
        )
        val content = Files.readString(generated)
        Then("the generated Scala code preserves the model semantics")
        content should include ("package textus.user.account")
        content should include ("object DomainComponent")
      }

      "modeler-scala merges Entity Event and top-level Event definitions" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/event-metadata-mixed.dox")
        val out = base.resolve("target/test-generated/modeler-scala-event-metadata-mixed")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        val content = Files.readString(generated)
        Then("the generated Scala code preserves the model semantics")
        content should include ("name = \"person.created\"")
        content should include ("name = \"system.heartbeat\"")
        content should include ("name = \"system.alert\"")
        content should include ("category = org.goldenport.cncf.event.CmlEventCategory.ActionEvent")
        content should include ("category = org.goldenport.cncf.event.CmlEventCategory.NonActionEvent")
        content should include ("actionName = Some(\"system.pulse\")")
        content should include ("selectors = Map(\"level\" -> \"warn\")")
      }

      "modeler-scala emits routing/subscription definitions from CML" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("src/test/resources/modeler/event-routing-subscription.dox")
        val out = base.resolve("target/test-generated/modeler-scala-event-routing-subscription")
        delete_recursively(out)
        Files.createDirectories(out.getParent)

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        val content = Files.readString(generated)
        Then("the generated Scala code preserves the model semantics")
        content should include ("def eventRoutingDefinitions: Vector[org.goldenport.cncf.event.CmlRoutingDefinition] = Vector(")
        content should include ("name = \"crm-route\"")
        content should include ("topic = Some(\"crm.events\")")
        content should include ("service = Some(\"person\")")
        content should include ("partition = Some(\"organization\")")
        content should include ("def eventSubscriptionDefinitions: Vector[org.goldenport.cncf.event.CmlSubscriptionDefinition] = Vector(")
        content should include ("name = \"person-sync\"")
        content should include ("eventName = \"person.created\"")
        content should include ("route = org.goldenport.cncf.event.DispatchRoute.Unicast")
        content should include ("target = Some(\"targetId\")")
        content should include ("actionName = \"person.sync\"")
        content should include ("declaredTargetUpperBound = 2")
        content should include ("activation = Some(org.goldenport.cncf.event.EntityActivationMode.KeepResident)")
      }

      "modeler-scala emits SmartDox RELATIONSHIP metadata and child bindings" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-generated/modeler-scala-relationship-child-binding.dox")
        val out = base.resolve("target/test-generated/modeler-scala-relationship-child-binding-out")
        delete_recursively(out)
        write_file(input,
        """# COMPONENT
          |
          |## Domain
          |
          |# ENTITY
          |
          |## SalesOrder
          |
          |### ATTRIBUTE
          |
          || name  | type     | multiplicity |
          ||-------+----------+--------------|
          || id    | entityid | 1            |
          || title | string   | 1            |
          |
          |## SalesOrderLine
          |
          |### ATTRIBUTE
          |
          || name    | type     | multiplicity |
          ||---------+----------+--------------|
          || id      | entityid | 1            |
          || orderId | entityid | 1            |
          || lineNo  | int      | 1            |
          |
          |# VALUE
          |
          |## RegisterOrder
          |
          |- input-kind :: COMMAND
          |
          |### ATTRIBUTE
          |
          || name  | type           | multiplicity |
          ||-------+----------------+--------------|
          || title | string         | 1            |
          || lines | SalesOrderLine | *            |
          |
          |## RegisterOrderResult
          |
          |### ATTRIBUTE
          |
          || name      | type     | multiplicity |
          ||-----------+----------+--------------|
          || entity_id | entityid | 1            |
          |
          |# RELATIONSHIP
          |
          |## SalesOrder.lines
          |
          |### KIND
          |
          |composition
          |
          |### SOURCE
          |
          |SalesOrder
          |
          |### TARGET
          |
          |SalesOrderLine
          |
          |### STORAGE
          |
          |child-parent-id-field
          |
          |### PARENT ID FIELD
          |
          |orderId
          |
          |### SORT ORDER FIELD
          |
          |lineNo
          |
          |### MULTIPLICITY
          |
          |one-to-many
          |
          |### LIFECYCLE
          |
          |dependent
          |
          |# SERVICE
          |
          |## OrderService
          |
          |### OPERATION
          |
          |#### registerOrder
          |
          |##### TYPE
          |
          |COMMAND
          |
          |##### INPUT
          |
          |###### TYPE
          |
          |RegisterOrder
          |
          |##### OUTPUT
          |
          |###### TYPE
          |
          |RegisterOrderResult
          |
          |##### CHILD ENTITY BINDING
          |
          |###### RELATIONSHIP
          |
          |SalesOrder.lines
          |
          |###### INPUT
          |
          |lines
          |
          |###### SOURCE ENTITY ID
          |
          |entity-create-result
          |""".stripMargin
        )

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        val content = Files.readString(generated)
        Then("the generated Scala code preserves the model semantics")
        content should include ("override def relationshipDefinitions: Vector[org.goldenport.cncf.operation.CmlEntityRelationshipDefinition] = Vector(")
        content should include ("""name = "SalesOrder.lines"""")
        content should include ("""kind = "composition"""")
        content should include ("""storageMode = "child-parent-id-field"""")
        content should include ("""parentIdField = Some("orderId")""")
        content should include ("""childEntityBindings = Vector(org.goldenport.cncf.operation.CmlOperationChildEntityBinding""")
        content should include ("""relationshipName = Some("SalesOrder.lines")""")
        content should include ("""inputParameter = "lines"""")
        content should include ("""sortOrderField = Some("lineNo")""")
      }

      "modeler-scala emits embedded value object relationship metadata" in {
        Given("a CML source model for Scala component generation")
        val base = Paths.get(sys.props("user.dir")).toAbsolutePath.normalize()
        val input = base.resolve("target/test-generated/modeler-scala-embedded-value-relationship.dox")
        val out = base.resolve("target/test-generated/modeler-scala-embedded-value-relationship-out")
        delete_recursively(out)
        write_file(input,
        """# COMPONENT
          |
          |## Domain
          |
          |# ENTITY
          |
          |## SalesOrder
          |
          |### ATTRIBUTE
          |
          || name            | type            | multiplicity |
          ||-----------------+-----------------+--------------|
          || id              | entityid        | 1            |
          || shippingAddress | ShippingAddress | ?            |
          |
          |# VALUE
          |
          |## ShippingAddress
          |
          |### ATTRIBUTE
          |
          || name       | type   | multiplicity |
          ||------------+--------+--------------|
          || line1      | string | 1            |
          || postalCode | string | 1            |
          |
          |# RELATIONSHIP
          |
          |## SalesOrder.shippingAddress
          |
          |### KIND
          |
          |composition
          |
          |### SOURCE
          |
          |SalesOrder
          |
          |### TARGET
          |
          |ShippingAddress
          |
          |### STORAGE
          |
          |embedded-value-object
          |
          |### VALUE FIELD
          |
          |shippingAddress
          |
          |### MULTIPLICITY
          |
          |zero-or-one
          |
          |### LIFECYCLE
          |
          |dependent
          |
          |# SERVICE
          |
          |## OrderService
          |""".stripMargin
        )

        When("Cozy generates Scala source from the model")
        cozy.Cozy.main(Array("modeler-scala", input.toString, "--save", out.toString.toString))

        val generated = out.resolve(
        "target/scala-3.3.8/src_managed/main/scala/domain/DomainComponent.scala"
        )
        val content = Files.readString(generated)
        Then("the generated Scala code preserves the model semantics")
        content should include ("""name = "SalesOrder.shippingAddress"""")
        content should include ("""targetEntityName = "ShippingAddress"""")
        content should include ("""targetModelKind = "value"""")
        content should include ("""storageMode = "embedded-value-object"""")
        content should include ("""valueField = Some("shippingAddress")""")
        content should not include ("""relationshipName = Some("SalesOrder.shippingAddress")""")
      }

    }
  }
}
