project:
  namespace: org.example.fixture
  id: Sales
  kind: car
  component:
    version: 0.1.0-SNAPSHOT

build:
  scalaVersion: "3.3.8"
  cozyVersion: "0.3.3-SNAPSHOT"
  dependencies:
    compile:
      - "org.goldenport::goldenport-cncf:0.5.3-SNAPSHOT"
    test:
      - "org.scalatest::scalatest:3.2.19"
